<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Wolfstare.Core\Wolfstare.Core.csproj" />
    <ProjectReference Include="..\Wolfstare.Contracts\Wolfstare.Contracts.csproj" />
    <ProjectReference Include="..\Wolfstare.Enforcement\Wolfstare.Enforcement.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.19" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="9.0.9" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="9.0.9" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
